<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 13:29:04.
 */
class add_stockTest extends PHPUnit\Framework\TestCase {

    /**
     * @var add_stock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new add_stock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers add_stock::main
     * @todo   Implement testMain().
     */
    public function testMain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
