    <?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 12:02:43.
 */
require_once 'D:\NetBeansProjects\302cem-group7-project\public\php\add_order_history.php';
class add_order_historyTest extends PHPUnit\Framework\TestCase
{
    /**
     * @var Add_Order_History
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Add_Order_History;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Add_Order_History::main
     * @todo   Implement testMain().
     */
    public function testMain()
    {
        //Setting up all the required variables
        $_POST = array('orderDetail'=>"test", 'fname'=>"testxw", 'email'=>"testxw@gmail.com", 'address'=>"testaddr");
        $_COOKIE = array('userid'=>1);
        
        //Assert the response
        $expected = json_encode(array("status"=>1, "message"=>"Order added."));
        $this->expectOutputString($expected);
        $this->object->main();
    }
}
