<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 12:02:43.
 */
require_once '../../302cem-group7-project/public/php/update_cart.php';


class cart_pageIntegrationTest extends PHPUnit\Framework\TestCase
{
    /**
     * @var Add_Order_History
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new update_cart;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Add_Order_History::main
     * @todo   Implement testMain().
     */
    
    public function test_update() {
        $_POST = array("product"=>"[{\"isbn\":\"4\",\"name\":\"4\",\"image\":\"../resources/images/The Return of the Condor Heroes.jpg\",\"quantity\":1,\"price\":\"362.00\",\"og_quantity\":\"16\"},{\"isbn\":\"69420\",\"name\":\"The Anarchist Cookbook\",\"image\":\"../resources/images/ac.jpg\",\"quantity\":16,\"price\":\"50.00\",\"og_quantity\":\"31\"}]", "totalincart"=>1);
        $_COOKIE = array("userid"=>5);
        
        //Assert the response
        $expected = json_encode(array("status"=>1, "message"=>"Successfully added."));
        $this->expectOutputString($expected);
        $this->object->main();
    }
    
    public function test_delete() {
        $_POST = array("product"=>"", "totalincart"=>1);
        $_COOKIE = array("userid"=>7);
        
        //Assert the response
        $expected = json_encode(array("status"=>0, "message"=>"Successfully deleted."));
        $this->expectOutputString($expected);
        $this->object->main();
    }
}

