<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 12:02:43.
 */
require_once '../../302cem-group7-project/public/php/cart.php';
class cartTest extends PHPUnit\Framework\TestCase
{
    /**
     * @var cart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new cart;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Add_Order_History::main
     * @todo   Implement testMain().
     */
    public function testMain()
    {
         $_POST = array('product_isbn'=>"testisbn", 'quantity'=>1);
         $this->object->main();
    }
}
