<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 15:09:34.
 */

require_once '../../302cem-group7-project/public/php/checkout_submit.php';

class checkout_submitTest extends PHPUnit\Framework\TestCase {

    /**
     * @var Checkout_Submit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Checkout_Submit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Checkout_Submit::main
     * @todo   Implement testMain().
     */
    public function testMain() {
        $_POST = array('name'=>"testbxy", 'email'=>"testxy@gmail.com", 'address'=>"testaddr.com", 'cart'=>"testcart");
        $_COOKIE = array('userid'=>1);
        
        //Assert the response
        $expected = json_encode(array("status"=>1, "message"=>"Checkout success"));
        $this->expectOutputString($expected);
        $response = $this->object->main();
    }

}
