<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 15:35:05.
 */

require_once '../../302cem-group7-project/public/php/checkout_user_profile.php';

class checkout_user_profileTest extends PHPUnit\Framework\TestCase {

    /**
     * @var Checkout_User_Profile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Checkout_User_Profile;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Checkout_User_Profile::main
     * @todo   Implement testMain().
     */
    public function testMain() {
        $_COOKIE = array('userid'=>1);
        
//        $expected = json_encode(array("status" => 1, "message" => "Search Result Returned.", "result" => $queryresult));
//        $this->expectOutputString($expected);
        $response = $this->object->main();
        $this->assertTrue($response);
    }
    
    public function testUserNotExist() {
        $_COOKIE = array('userid'=>9999);
        
        $expected = json_encode(array("status" => 0, "message" => "User doesn't exist."));
        $this->expectOutputString($expected);
        $response = $this->object->main();
    }
    
    public function testUserAddressNotExist() {
        $_COOKIE = array('userid'=>2);
        
        $expected = json_encode(array("status" => 0, "message" => "User address doesn't exist."));
        $this->expectOutputString($expected);
        $response = $this->object->main();
    }

}
