<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 12:02:43.
 */
require_once '../../302cem-group7-project/public/php/checkout_add_address.php';
class checkout_add_addressTest extends PHPUnit\Framework\TestCase
{
    /**
     * @var cart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Checkout_Add_Address;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Add_Order_History::main
     * @todo   Implement testMain().
     */
    public function testMain()
    {   
        $_POST = array('newAddressModal'=>"addresstest");
        $_COOKIE = array('userid'=>1);
        
        $expected = json_encode(array("status"=>1, "message"=>"Address updated successfully!"));
        $this->expectOutputString($expected);
        $response = $this->object->main();
    }
}
