<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 12:02:43.
 */
require_once '../../302cem-group7-project/public/php/detail_product.php';

class detail_productTest extends PHPUnit\Framework\TestCase {

    /**
     * @var Add_Order_History
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new detail_product;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Add_Order_History::main
     * @todo   Implement testMain().
     */
    public function test_detail_product() {
        $_POST = array('isbn' => "69420");
        $response = $this->object->main();
        $this->assertTrue($response);
    }
    
    public function test_detail_product_fail() {
        $_POST = array('isbn' => null);
        $expected = json_encode(array("status" => 0, "message" => "Product fail show."));
        $this->expectOutputString($expected);
        $this->object->main();
        
//        $response = $this->object->main();
//        $this->assertFalse($response);
    }

}
