<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 12:02:43.
 */
require_once '../../302cem-group7-project/public/php/check_user_cart.php';
require_once '../../302cem-group7-project/public/php/stock.php';
require_once '../../302cem-group7-project/public/php/add_to_cart.php';

class homepage_intergrationTest extends PHPUnit\Framework\TestCase {

    /**
     * @var Add_Order_History
     */
    protected $object1;
    protected $object2;
    protected $object3;
    protected $object4;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object1 = new Stock;
        $this->object2 = new Check_User_Cart;
        $this->object3 = new Add_To_Cart;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Add_Order_History::main
     * @todo   Implement testMain().
     */
    public function test_get_book(): void {
        $response = $this->object1->main();
        $this->assertTrue($response);
    }

    public function test_get_user_cart() {
        $_COOKIE = array('userid' => 1);

//        $expected = json_encode(array("status"=>1, "message"=>"Address updated successfully!"));
//        $this->expectOutputString($expected);
        $response = $this->object2->main();
        $this->assertTrue($response);
    }

    public function test_cart_insert_to_database() {
        //userid need differnt value
        $_COOKIE = array('userid' => 1);
        $_POST = array('product' => "productTest", 'totalincart' => 1);

        $expected = json_encode(array("status" => 1, "message" => "Successfully added into cart"));
        $this->expectOutputString($expected);
        $this->object3->main();
    }

}
