<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-12 at 16:03:09.
 */
require_once '../../302cem-group7-project/public/php/reduce_book_quantity.php';

class Reduce_Book_QuantityTest extends PHPUnit\Framework\TestCase {

    /**
     * @var Reduce_Book_Quantity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Reduce_Book_Quantity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Reduce_Book_Quantity::main
     * @todo   Implement testMain().
     */
    public function testMain() {

        //if wanna test gotta change quantity to something diff from database else will fail
        $_POST = array("product"=>'[{"isbn":"5941460992040","name":"The Return of the Condor Heroes","quantity":3,"price":"362.00","og_quantity":"16"}]');

        $expected = json_encode(array("status"=>1, "message"=>"Search Result Returned."));
        $this->expectOutputString($expected);
        $this->object->main();
    }
    
    public function testMainFail() {

        $_POST = array("product"=>'[{"isbn":"69696969","name":"The Return of the Condor Heroes","quantity":3,"price":"362.00","og_quantity":"16"}]');

        $expected = json_encode(array("status"=>0, "message"=>"Search Result Failed."));
        $this->expectOutputString($expected);
        $this->object->main();
    }

}
