<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-12 at 16:43:26.
 */
require_once '../../302cem-group7-project/public/php/stock_update_book.php';
class Stock_Update_BookTest extends PHPUnit\Framework\TestCase {

    /**
     * @var Stock_Update_Book
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Stock_Update_Book;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Stock_Update_Book::main
     * @todo   Implement testMain().
     */
    
    
    public function testMain() {
        //if testing, change old_isbn and detail value
        $_FILES['detail-image'] = array('name' => 'default_book.png', 'size'=>1000, 'tmp_name' => 'C:\xampp\tmp\default_book.png');
        $_POST = array('old_isbn'=>"whatever2",'detail-isbn'=>"whatever3", 'detail-name-input'=>"nameTest2", 'detail-author-input'=>"authorTest2", 'detail-date'=>"dateTest2", 'detail-des'=>"descTest2", 'detail-tp'=>12, 'detail-rp'=>12, 'detail-quantity'=>12);
        
        $expected = json_encode(array("status"=>1, "message"=>"The book with ISBN: whatever2 has been updated."));
        $this->expectOutputString($expected);
        $this->object->main();
    }
    
    public function testMainFail() {
        //if testing, change old_isbn value
        $_FILES['detail-image'] = array('name' => 'default_book.png', 'size'=>1000, 'tmp_name' => 'C:\xampp\tmp\default_book.png');
        $_POST = array('old_isbn'=>"whatever2",'detail-isbn'=>"whatever2", 'detail-name-input'=>"nameTest2", 'detail-author-input'=>"authorTest2", 'detail-date'=>"dateTest2", 'detail-des'=>"descTest2", 'detail-tp'=>12, 'detail-rp'=>12, 'detail-quantity'=>12);
        
        $expected = json_encode(array("status"=>0, "message"=>"An error has occurred when inserting."));
        $this->expectOutputString($expected);
        $this->object->main();
    }

}
