<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-14 at 13:43:31.
 */
require_once '../../302cem-group7-project/public/php/stock_delete_book.php';

class stock_delete_bookTest extends PHPUnit\Framework\TestCase {

    /**
     * @var Stock_Delete_Book
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Stock_Delete_Book;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Stock_Delete_Book::main
     * @todo   Implement testMain().
     */
    public function testMain() {
        //insert book with isbn "test" to run
        $_POST = array("isbn"=>"test", "image"=>"../resources/images/default_book.png");
        
        $expected = json_encode(array("status"=>1, "message"=>"The book has been deleted."));
        $this->expectOutputString($expected);
        $this->object->main();
    }
    
    public function testMainFail() {
        //insert book with isbn "test" to run
        $_POST = array("isbn"=>"", "image"=>"../resources/images/default_book.png");
        
        $expected = json_encode(array("status"=>0, "message"=>"An error has occurred during deletion."));
        $this->expectOutputString($expected);
        $this->object->main();
    }

}
