<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-07 at 13:11:06.
 */
require_once '../../302cem-group7-project/public/php/stock.php';
class stockTest extends PHPUnit\Framework\TestCase {

    /**
     * @var History
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Stock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers History::main
     * @todo   Implement testMain().
     */
    public function testDefaultGetBookData(): void {
        $response = $this->object->main();
        $this->assertTrue($response);
    }

    public function testSearchGetBookData(): void {
        //Search criteria
        $_POST = array('orderDetail'=>"The");
        
        $response = $this->object->main();
        $this->assertTrue($response);
    }
}
