<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-08 at 17:40:48.
 */
require_once 'D:\NetBeansProjects\302cem-group7-project\public\php\unit_test_example.php';
class CalculatorTest extends PHPUnit\Framework\TestCase {

    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Calculator::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(4, $this->object->add(2, 2));
    }

}
